spring:
  application:
    name: fake-store-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem



  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
              filters:
                - PreserveHostHeader
                - DedupeResponseHeader=Set-Cookie


            - id: user-endpoints
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/users/**

            - id: product-service
              uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/products/**

            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/orders/**

            - id: inventory-service-reservations
              uri: ${INVENTORY_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/reservations/**


server:
  port: ${PORT:8080}
  forward-headers-strategy: framework



